CREATE TABLE IF NOT EXISTS streaks(
id SERIAL PRIMARY KEY,
name VARCHAR(100) NOT NULL,
description TEXT,
count INT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);